spring:
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate:
      format_sql: true
      default_batch_fetch_size: 20
      jdbc.batch_size: 20
  datasource:
    #InMemory
    #url: jdbc:h2:mem:ferz
    #tcp: jdbc:h2:tcp://localhost:9092/mem:ferz
    #Absolute
    url: jdbc:h2:D:/db/ferz
    #tcp: jdbc:h2:tcp://localhost:9092/D:/db/ferz
    # Relative
    #url: jdbc:h2:./db/ferz
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console.enabled: true
  data.rest:
    basePath: /api
    returnBodyOnCreate: true
  #  security:
  #    user:
  #      name: user
  #      password: password
  #      roles: USER
  logging:
    level:
      root: WARN
      lb.ferzshow: DEBUG
#      org.springframework.security.web.FilterChainProxy: DEBUG
# Jackson Serialization Issue Resolver
#  jackson:
#    visibility.field: any